name: AnimalEconomy
main: com.animaleconomy.AnimalEconomy
version: 0.0.2
api-version: 1.16
author: mrbear25
softdepend: [PlaceholderAPI, Plan]
description: Animal Economy
commands:
  ae:
    description: Додати, зняти або встановити вбивства мобів для гравця.
    usage: /ae <add|remove|set> <player> <mob> <count>
    permission: ae.admin